(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'sha1' is not defined"
p3
sS'layer'
p4
S'/home/salmonmoose/web2py/applications/tombola/controllers/key.py'
p5
sS'code'
p6
S'<code object <module> at 0x6fffeee2e30, file "/home/salmonmoose/web2py/applications/tombola/controllers/key.py:index", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/salmonmoose/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/home/salmonmoose/web2py/applications/tombola/controllers/key.py:index", line 15, in <module>\n  File "/home/salmonmoose/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/salmonmoose/web2py/applications/tombola/controllers/key.py:index", line 8, in index\nNameError: global name \'sha1\' is not defined\n'
p11
s.